# Generated by Django 2.2.4 on 2019-08-20 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaderboard',
            old_name='player',
            new_name='name',
        ),
    ]
