# Generated by Django 2.2.4 on 2019-08-20 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0002_auto_20190820_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaderboard',
            name='winnings',
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='country',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='name',
            field=models.CharField(max_length=80),
        ),
    ]
