# Generated by Django 2.2.4 on 2019-08-20 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0003_auto_20190820_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboard',
            name='winnings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
            preserve_default=False,
        ),
    ]
